# Generated by Django 5.0.2 on 2024-02-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
