# Generated by Django 5.0.2 on 2024-03-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Simulator', '0002_delete_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Process_name', models.CharField(max_length=10, verbose_name='Process Name')),
                ('Arrival_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Arrival Time')),
                ('Burst_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Burst Time')),
                ('Turnaround_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Turnaround Time')),
                ('Waiting_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Waiting Time')),
            ],
        ),
    ]
