# Generated by Django 5.0.2 on 2024-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0004_process_completion_time_alter_process_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='Arrival_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Arrival_time'),
        ),
        migrations.AlterField(
            model_name='process',
            name='Burst_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Burst_time'),
        ),
        migrations.AlterField(
            model_name='process',
            name='Completion_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Completion_time'),
        ),
        migrations.AlterField(
            model_name='process',
            name='Process_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Process_name'),
        ),
        migrations.AlterField(
            model_name='process',
            name='Turnaround_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Turnaround_time'),
        ),
        migrations.AlterField(
            model_name='process',
            name='Waiting_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Waiting_time'),
        ),
    ]
